[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpterm"
description = "Library for AI assistant tasks"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "python-dotenv"
]

[tool.hatch.version]
path = "gpterm/__init__.py"
